services:
  traefik:
    image: traefik:latest
    container_name: traefik_web_hosting
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--accessLog=true"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - tugas_api_network

  golang_api:
    # Saya tidak butuh build karena di local sudah pernah membuatnya di project lain
    image: web-hosting-golang:latest
    # Gunakan build jika bapak mau mencoba
    # build: ./.docker/golang.Dockerfile
    container_name: tugas_api_go
    restart: unless-stopped
    env_file:
      - .env
      - ./internal/golang/.env
    working_dir: /golang
    volumes:
      - ./internal/golang/:/golang
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-router.rule=PathPrefix(`/api/menu`) || PathPrefix(`/api/category`)"
      - "traefik.http.routers.go-router.entrypoints=web"
      - "traefik.http.services.go-service.loadbalancer.server.port=8080"
    networks:
      - tugas_api_network

  php_api:
    build:
      context: .
      dockerfile: .docker/php-apache.Dockerfile
    container_name: tugas_api_php
    restart: unless-stopped
    env_file:
      - .env
      - ./internal/php/.env
    volumes:
      - ./internal/php:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php-router.rule=PathPrefix(`/api/order`) || PathPrefix(`/api/user`)"
      - "traefik.http.routers.php-router.entrypoints=web"
      - "traefik.http.services.php-service.loadbalancer.server.port=80"
    networks:
      - tugas_api_network

  db:
    image: "mysql:8.0"
    container_name: tugas_api_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/logs:/var/log/mysql
      - ./.docker/mysql/sql:/docker-entrypoint-initdb.d
    networks:
      - tugas_api_network

networks:
  tugas_api_network:
    driver: bridge
